# Generated by Django 3.2.6 on 2022-04-17 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='locaton',
            new_name='location',
        ),
    ]
